

services:
  nextcloud:
    container_name: "clout_nextcloud"
    image: nextcloud:latest
    depends_on:
      - db
    ports:
      - "8081:80"
    volumes:
      - "/home/clout/nextcloud/html:/var/www/html"
      
    environment:
      - PHP_MEMORY_LIMIT=4096M
      - PHP_UPLOAD_LIMIT=102400M
    networks:
      - pub
      - priv
    restart: always

  db:
    container_name: "clout_postgres"
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "/home/clout/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=test123
      - PGDATA=/var/lib/postgresql/data
    networks:
      - priv
    restart: always
  
  nginx_proxy:
    container_name: "clout_nginx_proxy"
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "/home/clout/nginx:/data"
      - "/home/clout/letsencrypt:/etc/letsencrypt"

networks:
  priv:
    name: "clout_private"
    driver: bridge
  pub:
    name: "clout_public"
    driver: bridge